<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_charged</name>
   <tag></tag>
   <elementGuidId>d377cd4c-a221-4cd8-867d-acf931ce383f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiTypography-root.makeStyles-titleAction-95.MuiTypography-body1.MuiTypography-displayInline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div[2]/div/div/div/div/div/div[2]/div[2]/p/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;transaction-action-b-ioRbrwM&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e6278f3-b511-4486-a8c2-0e30fb8ea1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root makeStyles-titleAction-95 MuiTypography-body1 MuiTypography-displayInline</value>
      <webElementGuid>9ef03f63-7549-4314-9804-247cc6ad4956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>transaction-action-b-ioRbrwM</value>
      <webElementGuid>2867e970-23b9-4349-b6be-24450e6b7b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> charged </value>
      <webElementGuid>bc2e6ce1-dde5-498e-96b4-51c32360b341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;makeStyles-root-1&quot;]/main[@class=&quot;makeStyles-content-19&quot;]/div[@class=&quot;MuiContainer-root makeStyles-container-20 MuiContainer-maxWidthMd&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-3&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;MuiPaper-root makeStyles-paper-86 MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-center MuiGrid-justify-content-xs-space-between&quot;]/div[@class=&quot;MuiGrid-root makeStyles-headline-89 MuiGrid-item&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-direction-xs-column MuiGrid-align-items-xs-flex-start&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item&quot;]/p[@class=&quot;MuiTypography-root makeStyles-title-94 MuiTypography-body1 MuiTypography-colorTextSecondary MuiTypography-gutterBottom&quot;]/span[@class=&quot;MuiTypography-root makeStyles-titleAction-95 MuiTypography-body1 MuiTypography-displayInline&quot;]</value>
      <webElementGuid>0a733d07-5fb9-4c97-b95d-08611d4b6af0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div/div/div/div/div[2]/div[2]/p/span[2]</value>
      <webElementGuid>5d76d8cc-d19f-4807-a637-145bffc58398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ted Parisian'])[1]/following::span[1]</value>
      <webElementGuid>132b675d-9b6b-4392-8891-18d7b25ef98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Detail'])[1]/following::span[2]</value>
      <webElementGuid>92c82da9-db1b-4fc8-aa04-326f707a3b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Darrel Ortiz'])[1]/preceding::span[1]</value>
      <webElementGuid>e23a2b9a-1023-41b8-9d2b-914e34db20d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+$100.00'])[1]/preceding::span[2]</value>
      <webElementGuid>b2cfa52d-955e-498b-88e6-091aafba32db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='charged']/parent::*</value>
      <webElementGuid>5b234584-1882-4125-8abb-52caf26ad1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span[2]</value>
      <webElementGuid>64589f63-a8da-4be9-98cf-efb6ed1d55d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' charged ' or . = ' charged ')]</value>
      <webElementGuid>3d5edd52-1b48-4cde-ae57-4f83fde6a1f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
